import { createFileRoute, notFound } from "@tanstack/react-router";
import { useEffect } from "react";
import { notes } from "@/data/notes";
import { courses } from "@/data/courses";

export const Route = createFileRoute("/app/library/$code/$lessonId/print")({
  head: ({ params }) => ({ meta: [{ title: `Study sheet — ${params.code} — Uniflow` }] }),
  component: PrintLesson,
});

function PrintLesson() {
  const { code, lessonId } = Route.useParams();
  const note = notes.find((n) => n.id === lessonId);
  const course = courses.find((c) => c.code === code);
  if (!note || !course) throw notFound();

  useEffect(() => {
    const t = setTimeout(() => window.print(), 600);
    return () => clearTimeout(t);
  }, []);

  // Extract sections from markdown-ish body
  const sections = note.body.split("\n## ").slice(1).map((s) => {
    const [head, ...rest] = s.split("\n");
    return { title: head, body: rest.join("\n").trim() };
  });

  // Generate "key questions" by inverting key sentences (mock)
  const questions = sections.slice(0, 5).flatMap((s) => [
    `Define / explain: ${s.title}.`,
    `Give a concrete example of ${s.title.toLowerCase()}.`,
  ]).slice(0, 10);

  return (
    <div className="min-h-screen bg-white text-black p-12 print:p-0 max-w-[800px] mx-auto font-serif">
      <style>{`
        @media print {
          @page { margin: 1.5cm; }
          body { background: white !important; }
          .no-print { display: none !important; }
        }
      `}</style>
      <div className="no-print mb-6 flex justify-end gap-2">
        <button onClick={() => window.print()} className="px-3 py-1.5 text-xs font-semibold border border-black/20 rounded">Print</button>
      </div>

      <header className="border-b-2 border-black pb-4 mb-6">
        <p className="text-xs uppercase tracking-widest text-black/60">Uniflow · {course.name} · Study sheet</p>
        <h1 className="text-3xl font-extrabold mt-2">{note.title}</h1>
      </header>

      <section className="mb-8">
        <h2 className="text-sm uppercase tracking-widest text-black/60 mb-3">Key definitions</h2>
        <div className="space-y-3 text-[13px] leading-relaxed">
          {sections.map((s) => (
            <div key={s.title}>
              <p className="font-bold">{s.title}</p>
              <p className="mt-1">{s.body}</p>
            </div>
          ))}
        </div>
      </section>

      <section>
        <h2 className="text-sm uppercase tracking-widest text-black/60 mb-3">Practice questions</h2>
        <ol className="list-decimal list-inside space-y-2 text-[13px]">
          {questions.map((q, i) => <li key={i}>{q}</li>)}
        </ol>
      </section>

      <footer className="mt-12 pt-4 border-t border-black/30 text-[10px] text-black/50 uppercase tracking-widest">
        Generated by Uniflow · {course.code} · {note.title}
      </footer>
    </div>
  );
}
