/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as InstitutionalRouteImport } from './routes/institutional'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTutorRouteImport } from './routes/app.tutor'
import { Route as AppQuizzesRouteImport } from './routes/app.quizzes'
import { Route as AppPlannerRouteImport } from './routes/app.planner'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppFocusRouteImport } from './routes/app.focus'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalRoute = InstitutionalRouteImport.update({
  id: '/institutional',
  path: '/institutional',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesRoute = AppQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppFocusRoute = AppFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/institutional': typeof InstitutionalRoute
  '/platform': typeof PlatformRoute
  '/resources': typeof ResourcesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/focus': typeof AppFocusRoute
  '/app/notes': typeof AppNotesRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/institutional': typeof InstitutionalRoute
  '/platform': typeof PlatformRoute
  '/resources': typeof ResourcesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/focus': typeof AppFocusRoute
  '/app/notes': typeof AppNotesRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/tutor': typeof AppTutorRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/institutional': typeof InstitutionalRoute
  '/platform': typeof PlatformRoute
  '/resources': typeof ResourcesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/focus': typeof AppFocusRoute
  '/app/notes': typeof AppNotesRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/institutional'
    | '/platform'
    | '/resources'
    | '/app/analytics'
    | '/app/focus'
    | '/app/notes'
    | '/app/planner'
    | '/app/quizzes'
    | '/app/tutor'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/institutional'
    | '/platform'
    | '/resources'
    | '/app/analytics'
    | '/app/focus'
    | '/app/notes'
    | '/app/planner'
    | '/app/quizzes'
    | '/app/tutor'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/institutional'
    | '/platform'
    | '/resources'
    | '/app/analytics'
    | '/app/focus'
    | '/app/notes'
    | '/app/planner'
    | '/app/quizzes'
    | '/app/tutor'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  InstitutionalRoute: typeof InstitutionalRoute
  PlatformRoute: typeof PlatformRoute
  ResourcesRoute: typeof ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional': {
      id: '/institutional'
      path: '/institutional'
      fullPath: '/institutional'
      preLoaderRoute: typeof InstitutionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tutor': {
      id: '/app/tutor'
      path: '/tutor'
      fullPath: '/app/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quizzes': {
      id: '/app/quizzes'
      path: '/quizzes'
      fullPath: '/app/quizzes'
      preLoaderRoute: typeof AppQuizzesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planner': {
      id: '/app/planner'
      path: '/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/focus': {
      id: '/app/focus'
      path: '/focus'
      fullPath: '/app/focus'
      preLoaderRoute: typeof AppFocusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppFocusRoute: typeof AppFocusRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppQuizzesRoute: typeof AppQuizzesRoute
  AppTutorRoute: typeof AppTutorRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppFocusRoute: AppFocusRoute,
  AppNotesRoute: AppNotesRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppQuizzesRoute: AppQuizzesRoute,
  AppTutorRoute: AppTutorRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  InstitutionalRoute: InstitutionalRoute,
  PlatformRoute: PlatformRoute,
  ResourcesRoute: ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
